export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"

export const INIT_ORGANIZATIONS = "INIT_ORGANIZATIONS"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION"
export const INIT_ONE_OGRANIZATION = "INIT_ONE_OGRANIZATION"
export const ADD_COMMENT = "ADD_COMMENT"

export const INIT_ORG_VACANCY = "INIT_ORG_VACANCY"

export const INIT_COMMENT = "INIT_COMMENT"

export const ADD_PHOTO = "ADD_PHOTO"
export const UPDATE_USER = "UPDATE_USER"
export const ADD_RESUME = "ADD_RESUME"

export const UPDATE_USER_From_ALL = "UPDATE_USER_From_ALL"
export const ADD_PHOTO_USER_FROM_ALL = "ADD_PHOTO_USER_FROM_ALL"
export const ADD_RESUME_USER_FROM_ALL="ADD_RESUME_USER_FROM_ALL"

export const INIT_REQUEST_STUDENTS = 'INIT_REQUEST_STUDENTS'
export const INIT_REQUEST_STUDENT_PARAMS = 'INIT_REQUEST_STUDENT_PARAMS'

export const ADD_VACANTION = 'ADD_VACANTION'
export const INIT_VACANTION = 'INIT_VACANTION'
export const INIT_ONE_VACANTION = 'INIT_ONE_VACANTION'
export const EDIT_ACTUAL_VACANTION = 'EDIT_ACTUAL_VACANTION'

export const INIT_ALL_STUDENTS = 'INIT_ALL_STUDENTS'
export const INIT_SEARCH_STUDENTS = 'INIT_SEARCH_STUDENTS'
